# 应用名称
#spring.application.name=shiro-jsp
# 应用服务 WEB 访问端口
#server.port=8080
#设置访问路径
#server.servlet.context-path=/shiro
#更换试图为jsp
#spring.mvc.view.prefix=/
#spring.mvc.view.suffix=.jsp
# 数据库驱动：
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 数据源名称
#spring.datasource.name=defaultDataSource
# 数据库连接地址
#spring.datasource.url=jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
# 数据库用户名&密码：
#spring.datasource.username=***
#spring.datasource.password=***
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  application:
    name: shiro-jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.148.78:3306/mybatis-plus?useSSL=false&useUnicode=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Admin123~.
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 121.196.148.78
      port: 6379
      database: 0
server:
  port: 8080
  servlet:
    context-path: /shiro
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    com:
      example: debug

